<?php include 'menu.phtml' ?>

			<section>
				<h2>- Article : <?= $post['title']?> -</h2>
				<p><?= $post['date']?></p>
				<?php if($post['image']!=false) : ?>
					<img src="picture/<?= $post['image'] ?>" alt="photo<?= $post['image']?>">
				<?php endif ?>
				<p><?= $post['content'] ?></p>
				<div class="tag">
					<?php if($tagsNumber>0) : ?>
						<p>Tags : </p>
						<?php foreach ($tags as $tag) : ?>
							<p><a href="tag.php?tag=<?= $tag['content'] ?>"><?= htmlentities($tag['content']) ?></a></p>
						<?php endforeach ?>
					<?php endif ?>
				</div>
				<?php if($nbComment>=1) : ?>
					<h3>Commentaires</h3>
				<?php endif ?>
				<?php foreach ($comments as $number => $comment) : ?>
					<p>
						<?= htmlentities($comment['name'])." : ".$comment['content'] ?>
					</p>
					<?php if(isset($_SESSION['name']) && $_SESSION['admin']==1) : ?>
					<form action="erasecomment.php?id=<?= $comment['id'] ?>" method="post">
						<button type="submit" onclick="return confirm('etes vous sur ?')">Surpprimer</button>
					</form>
					<?php endif ?>
				<?php endforeach ?>
				<h3>Ajouter un commentaire</h3>

				<?php if(isset($_SESSION['name'])) : ?>
					<div class="formcomment">
						<form action="" method="post">
							<textarea name="commentContent" id="commentContent" cols="50" rows="10" placeholder="contenu..."></textarea>
							<button type="submit">Envoyer</button>
						</form>
					</div>
				<?php else : ?>
					<a href="login.php">Vous devez vous connecter !</a>
				<?php endif ?>

				
			</section>

<?php include 'footer.phtml' ?>