<?php include 'menu.phtml' ?>

			<section>
				<h2>Inscription</h2>
				<div class="formuser">
					<form action="" method="post">

						<div class="clearfix">
							<label for="name">Nom</label><!-- 
							 --><input type="text" name="name" required>	
							</div>
						<?php if($takenUser) :  ?>
							<p><span>Le Nom est déjà pris<span></p>
						<?php endif ?>
						<?php if(isset($_POST['name']) && strlen($_POST['name'])<6) :  ?>
							<p>Le Nom doit comporter 6 caractères minimum</p>
						<?php endif ?>
						<div class="clearfix">
							<label for="mail">Mail</label><!-- 
							 --><input type="text" name="mail" required>
						</div>
						<?php if(isset($_POST['mail']) && filter_var($_POST['mail'], FILTER_VALIDATE_EMAIL)==false) :  ?>
							<p>Adresse mail non valide</p>
						<?php endif ?>
						<div class="clearfix">
							<label for="password">Mot de passe</label><!-- 
							 --><input type="text" name="password" required>
						</div>
						<?php if(isset($_POST['password']) && strlen($_POST['password'])<6) :  ?>
							<p>Le mdp doit comporter 6 caractères minimum</p>
						<?php endif ?>
						<button type="submit">Créer profil</button>
					</form>
				</div>
			</section>

<?php include 'footer.phtml' ?>