<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>BlogDamien</title>
		<link rel="stylesheet" href="css/styles.css">
		<link rel="stylesheet" href="css/normalize.css">
	</head>
	<body>
		<div class="wrapper">
			<header>
				<h1>TITRE</h1>
				<nav>
					<ul>
						<li><a href="index.php">Accueil</a></li><!-- 
						 --><li><a href="login.php">Connexion</a></li>
					</ul>
				</nav>
			</header>
			<section>
				<h2>Inscription</h2>
				<div class="form">
					<form action="" method="post">
						<div class="clearfix">
							<label for="name">Nom</label><!-- 
							 --><input type="text" name="name">					
						</div>
						<div class="clearfix">
							<label for="mail">Mail</label><!-- 
							 --><input type="text" name="mail">
						</div>
						<div class="clearfix">
							<label for="password">Mot de passe</label><!-- 
							 --><input type="text" name="password">
						</div>
						<button type="submit">Créer profil</button>
					</form>
				</div>
			</section>
		</div>
	</body>
</html>