<?php include 'menu.phtml' ?>

			<section>
				<h2>Espace Membre</h2>
				<div class="formuser">
					<form action="" method="post">
						<div class="clearfix">
							<label for="name">Nom</label><!-- 
							 --><input type="text" name="name">					
						</div>
						<div class="clearfix">
							<label for="password">Mot de passe</label><!-- 
							 --><input type="text" name="password">
						</div>
						<button type="submit">Se connecter</button>
					</form>
				</div>
				<a href="inscription.php">Pas encore inscrit ?</a>
			</section>
			
<?php include 'footer.phtml' ?>